[package]
name = "suffix_array_rs"
version = "0.1.0"
edition = "2021"
description = ""
authors = ["Marisa Hudspeth <mhudspeth@umass.edu>"]

[lib]
name = "suffix_array_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18.0", features = ["extension-module"] }
esaxx-rs = "0.1.0" 